#!/usr/bin/env bash
# Idempotent install for hey-jev on Debian (geekom or any Linux box).
# Asks for the systemd service name and all .env values (empty = skip),
# generates .env + hey-jev.service, installs venv + deps, starts the service.
set -e
cd "$(dirname "$0")"
CHECKOUT_DIR=$(dirname "$PWD")   # .env lives at the checkout root (config.py looks there)

ask() {
    # ask <prompt> <default> -> prints answer (default when empty)
    local prompt="$1" def="$2" ans
    if [ -n "$def" ]; then
        read -r -p "$prompt [$def]: " ans || ans="$def"
        echo "${ans:-$def}"
    else
        read -r -p "$prompt: " ans || ans=""
        echo "$ans"
    fi
}

ask_secret() {
    # same as ask but masks input; default shown as (set)
    local prompt="$1" def="$2" ans
    if [ -n "$def" ]; then
        read -r -s -p "$prompt [(set) — Enter to keep, type to replace]: " ans || ans=""
        echo "${ans:-$def}"
    else
        read -r -s -p "$prompt: " ans || ans=""
        echo "$ans"
    fi
}

SERVICE_NAME=$(ask "Systemd service name" "hey-jev")
echo "== apt packages"
sudo apt update
sudo apt install -y python3-venv python3-pip libportaudio2 playerctl \
    pipewire-alsa libasound2-plugins

echo "== venv + deps"
python3 -m venv .venv
.venv/bin/pip install --upgrade pip
.venv/bin/pip install -r requirements.txt

echo "== pre-download Whisper small.en (~250 MB, skipped if already cached)"
.venv/bin/python - <<'EOF' || echo "[warn] model download failed — it will retry on first voice turn"
from huggingface_hub import snapshot_download
p = snapshot_download("Systran/faster-whisper-small.en")
print("model cached at:", p)
EOF

echo "== optional languages"
echo "small.en understands English only. Other languages need the multilingual"
echo "'small' model (~470 MB, one model covers ~99 languages). Common codes:"
echo "  en English | hr Croatian | de German | sl Slovenian | it Italian |"
echo "  fr French | es Spanish | nl Dutch | pl Polish | ru Russian"
read -r -p "Languages to enable (comma-separated codes, empty = English only): " LANGS
LANGS=$(echo "$LANGS" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
NON_EN=$(echo "$LANGS" | tr ',' '\n' | grep -vx 'en' | tr '\n' ',' | sed 's/,$//')
if [ -n "$NON_EN" ]; then
    echo "-- downloading multilingual 'small' model (~470 MB, skipped if cached)"
    .venv/bin/python - <<'EOF' || echo "[warn] multilingual model download failed — rerun install.sh later"
from huggingface_hub import snapshot_download
p = snapshot_download("Systran/faster-whisper-small")
print("model cached at:", p)
EOF
    ALL_LANGS="en,$NON_EN"
    ALL_LANGS=$(echo "$ALL_LANGS" | sed 's/,$//')
else
    ALL_LANGS="${LANGS:-en}"
fi
echo "languages: $ALL_LANGS"

echo "== default source: real mic (skip monitors)"
MIC=$(pactl list short sources | awk '$3 != "" && /input/ && !/monitor/ {print $2; exit}')
if [ -n "$MIC" ]; then
    pactl set-default-source "$MIC" && echo "default source: $MIC"
else
    echo "no mic source found — set with: pactl set-default-source <name>"
fi

echo "== .env"
# existing values become defaults (Enter keeps them)
load_env_default() {
    local key="$1"
    [ -f "$CHECKOUT_DIR/.env" ] && grep -E "^$key=" "$CHECKOUT_DIR/.env" | head -1 | cut -d= -f2-
}
DEF_TS=$(load_env_default TYPESAFE_API_KEY)
DEF_KEV_URL=$(load_env_default KEV_URL)
DEF_KEV_KEY=$(load_env_default KEV_API_KEY)
DEF_OR=$(load_env_default OPENROUTER_API_KEY)
DEF_LLM=$(load_env_default LLM_MODEL)
DEF_LLM_MT=$(load_env_default LLM_MAX_TOKENS)
DEF_FISH=$(load_env_default FISH_AUDIO_API_KEY)
DEF_FRONT=$(load_env_default REMOTE_FRONT)
DEF_PORT=$(load_env_default REMOTE_PORT)
DEF_HOST=$(load_env_default REMOTE_HOST)
DEF_TOKEN=$(load_env_default REMOTE_TOKEN)
DEF_TOKS=$(load_env_default REMOTE_TOKENS)
DEF_SKL=$(load_env_default SERVER_KEY_LIMIT)
DEF_NTFY=$(load_env_default NTFY_URL)
DEF_ALERT=$(load_env_default ALERT_MESSAGE)

TS=$(ask_secret "TYPESAFE_API_KEY (decision backend 2)" "$DEF_TS")
KEV_URL=$(ask "KEV_URL (decision backend 1, e.g. https://…/v1-base)" "$DEF_KEV_URL")
KEV_KEY=$(ask_secret "KEV_API_KEY" "$DEF_KEV_KEY")
OR=$(ask_secret "OPENROUTER_API_KEY (backend 3 + LLM answers)" "$DEF_OR")
LLM=$(ask "LLM_MODEL" "${DEF_LLM:-anthropic/claude-haiku-4.5}")
LLM_MT=$(ask "LLM_MAX_TOKENS" "${DEF_LLM_MT:-300}")
FISH=$(ask_secret "FISH_AUDIO_API_KEY (required — the voice)" "$DEF_FISH")
FRONT=$(ask "REMOTE_FRONT (none | npm | tunnel)" "${DEF_FRONT:-tunnel}")
PORT=$(ask "REMOTE_PORT" "${DEF_PORT:-8765}")
RHOST=$(ask "REMOTE_HOST (127.0.0.1 = tunnel/local only)" "${DEF_HOST:-127.0.0.1}")
RTOK=$(ask_secret "REMOTE_TOKEN (gate for web clients)" "$DEF_TOKEN")
TOKS=$(ask "REMOTE_TOKENS (extra per-device tokens, comma-separated, empty = none)" "$DEF_TOKS")
SKL=$(ask "SERVER_KEY_LIMIT (free server-key turns per device)" "${DEF_SKL:-10}")
NTFY=$(ask "NTFY_URL (https://ntfy.sh/<topic>, empty = no push)" "$DEF_NTFY")
ALERT=$(ask "ALERT_MESSAGE (default alert for label-less timers)" "$DEF_ALERT")

cat > "$CHECKOUT_DIR/.env" <<EOF
# generated by install.sh
KEV_URL=$KEV_URL
KEV_API_KEY=$KEV_KEY
TYPESAFE_API_KEY=$TS
OPENROUTER_API_KEY=$OR
LLM_MODEL=$LLM
LLM_MAX_TOKENS=$LLM_MT
FISH_AUDIO_API_KEY=$FISH
REMOTE_FRONT=$FRONT
REMOTE_PORT=$PORT
REMOTE_HOST=$RHOST
REMOTE_TOKEN=$RTOK
REMOTE_TOKENS=$TOKS
SERVER_KEY_LIMIT=$SKL
NTFY_URL=$NTFY
ALERT_MESSAGE=$ALERT
WHISPER_LANGUAGES=$ALL_LANGS
EOF
chmod 600 "$CHECKOUT_DIR/.env"

echo "== service: $SERVICE_NAME"
bash deploy-service.sh "$SERVICE_NAME"

echo "== public HTTPS (cloudflared)"
CLOUDFLARED_BIN=$(command -v cloudflared || true)
TUNNEL_NAME=$(ask "cloudflared tunnel name (the one you want to expose through)" "")
CERT_FILE=$(ls "$RUN_HOME/.cloudflared"/*.pem 2>/dev/null | head -1 || true)
if [ -z "$CLOUDFLARED_BIN" ]; then
    echo "-- cloudflared not installed. Try:"
    echo "   sudo apt install cloudflared   # if the cloudflare repo is configured"
    echo "   or download: curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /tmp/cloudflared && sudo mv /tmp/cloudflared /usr/local/bin/cloudflared"
    echo "   then: cloudflared tunnel login   # opens a browser"
    CLOUDFLARED_BIN=$(command -v cloudflared || true)
    [ -z "$CLOUDFLARED_BIN" ] && echo "[warn] continuing without cloudflared — the server stays local/LAN only" || true
fi

SITE_NAME=$(ask "Public hostname for the web remote (e.g. hey-jev.your-domain.tld)" "")
TUNNEL_UUID=$(ls "$RUN_HOME/.cloudflared"/*.json 2>/dev/null | head -1 | xargs -r basename | sed 's/\.json$//')
DNS_OK="no"
if [ -n "$CLOUDFLARED_BIN" ] && [ -n "$TUNNEL_UUID" ] && [ -n "$SITE_NAME" ]; then
    if $CLOUDFLARED_BIN tunnel route dns "$TUNNEL_UUID" "$SITE_NAME" 2>&1 | tail -1; then
        DNS_OK="yes"
    fi
fi
INGRESS_OK="no"
if [ -n "$CLOUDFLARED_BIN" ] && [ -n "$SITE_NAME" ]; then
    CFG="$RUN_HOME/.cloudflared/config.yml"
    if [ -f "$CFG" ]; then
        if grep -q "$SITE_NAME" "$CFG"; then
            echo "-- ingress for $SITE_NAME already present"
            INGRESS_OK="yes"
        else
            python3 - "$CFG" "$SITE_NAME" "$PORT" <<'PYEOF'
import sys
cfg_path, site, port = sys.argv[1], sys.argv[2], sys.argv[3]
cfg = open(cfg_path).read()
indent = "  - hostname: " in cfg and "  " or ""
lines = cfg.splitlines()
out, inserted = [], False
for i, line in enumerate(lines):
    if line.strip().startswith("- hostname:") and not inserted:
        indent = line[: len(line) - len(line.lstrip())]
        out.append(f"{indent}- hostname: \"{site}\"")
        out.append(f"{indent}  service: http://localhost:{port}")
        out.append("")
        inserted = True
    out.append(line)
if not inserted:
    out += [f"{indent}- hostname: \"{site}\"", f"{indent}  service: http://localhost:{port}",
            f"{indent}  service: http_status:404" if False else ""]
    out = [l for l in out if l != "" or True]
    if not inserted:
        out.append(f'{indent}- hostname: "{site}"')
        out.append(f"{indent}  service: http://localhost:{port}")
open(cfg_path, "w").write("\n".join(out) + "\n")
print(f"ingress added: {site} -> http://localhost:{port}")
PYEOF
            if grep -q "$SITE_NAME" "$CFG"; then INGRESS_OK="yes"; fi
        fi
    else
        echo "-- no $CFG config.yml found. Create one:"
        echo "   $CLOUDFLARED_BIN tunnel create <tunnel-name>"
        echo "   then write $CFG with:"
        echo "     tunnel: <tunnel-id>"
        echo "     credentials-file: $RUN_HOME/.cloudflared/<tunnel-id>.json"
        echo "     ingress:"
        echo "       - hostname: $SITE_NAME"
        echo "         service: http://localhost:$PORT"
        echo "       - service: http_status:404"
    fi
    if systemctl --user list-units --all --no-legend 2>/dev/null | grep -qi cloudflared; then
        systemctl --user restart cloudflared 2>/dev/null || \
        systemctl --user restart cloudflared-nimesin.site 2>/dev/null || true
        INGRESS_OK="yes"
    elif systemctl list-units --all --no-legend 2>/dev/null | grep -qi cloudflared; then
        UNIT=$(systemctl list-units --all --no-legend | grep -i cloudflared | awk '{print $1}' | head -1)
        sudo systemctl restart "$UNIT"
        INGRESS_OK="yes"
    else
        echo "-- cloudflared not running as a service. Test manually:"
        echo "   $CLOUDFLARED_BIN tunnel run <tunnel-name>"
        echo "   then install as a service: $CLOUDFLARED_BIN service install"
    fi
fi

echo "== summary"
echo "  service:      $SERVICE_NAME (systemctl status $SERVICE_NAME)"
echo "  local:        http://127.0.0.1:$PORT/health"
[ "$DNS_OK" = "yes" ] && echo "  dns route:    $SITE_NAME -> tunnel ✓"
[ "$INGRESS_OK" = "yes" ] && echo "  ingress:      $SITE_NAME -> localhost:$PORT ✓"
if [ "$DNS_OK" = "yes" ] && [ "$INGRESS_OK" = "yes" ]; then
    echo "  public:       https://$SITE_NAME/health  (test from another device)"
else
    echo "  public:       NOT fully wired — follow the instructions above, then:"
    echo "                sudo systemctl restart cloudflared (or --user variant)"
fi

echo "== done"
